# https://taskfile.dev

version: "3"

vars:
  PROJECT: geo

tasks:

  default:
    desc: run
    cmds:
      -  mamba run --live-stream -n {{.PROJECT}} python -m app

  stop:
    desc: stop the server
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user stop {{.PROJECT}}'

  restart:
    desc: restart the service
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user restart {{.PROJECT}}'

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push  || true

  pull:
    desc: pulls from git
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/{{.PROJECT}};git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  logs:
    desc: monitor logs
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;journalctl --user -u {{.PROJECT}} -f' | ccze -A

  systemd-exec:
    desc: systemd exec
    cmds:
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} python -m app

  export:
    desc: export env
    cmds:
      - mamba env export --no-builds --ignore-channels  -n {{.PROJECT}} > environment.yml

  export-remote:
    desc: export env
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/{{.PROJECT}};mamba env export --no-builds -n {{.PROJECT}} > environment-remote.yml'
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/{{.PROJECT}};task push'
      - git pull

  install:
    desc: update package
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/botyo;mamba run --live-stream -n {{.PROJECT}} pip install {{.CLI_ARGS}} -U'
      - task: export-remote
      - task: deploy

  deploy:
    desc: all
    cmds:
      - task: pp
      - task: restart

  cli:
    desc: run flask geo locally
    cmds:
      - mamba run --live-stream -n {{.PROJECT}} flask {{.CLI_ARGS}}

  redis:
    desc: open redis-cli
    cmds:
      - redis-cli $REDIS_CLI

  web-deploy:
    desc: deploy
    dir: web
    cmds:
      - ng build --configuration production --service-worker
      - tar cfz dist.tgz dist/geo
      - scp dist.tgz open:/var/www/geo
      - ssh open rm -rf /var/www/geo/dist
      - ssh open tar zxf /var/www/geo/dist.tgz --directory /var/www/geo
      - ssh open rm /var/www/geo/dist.tgz